# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        uses: xpol/setup-lua@v0.2
      - uses: leafo/gh-actions-luarocks@v4
      - name: test
        run: |
          luarocks install busted \
          && luarocks install luacov \
          && busted -c 
      - uses: codecov/codecov-action@v2.1.0
